### ISSUE TITLE
how to set bootstrap modal options

### ISSUE THREAD

**Issue by pajooh** [Bloodsucker/meteor-bootstrap3-modals#1]
like modal size, etc.

**Comment by Bloodsucker** [comment]
Hi!

It's good to know you liked my small package :)

I have added this feature, and some others to personalize the modal quite easily. You can find them in the latest version.

An example:

``` javascript
    bModal = BModals.showNew('My Template', function () {
        return MyColl.findOne(docId);
    }, {
        size: 'modal-lg',
    });
```

Hope you find it useful.
